project_id = "wmumnlhzjvscoyuqljyj"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.capture-booking-payment]
    verify_jwt = false
  [functions.complete-booking-payout]
    verify_jwt = false
  [functions.create-booking-payment]
    verify_jwt = false
  [functions.get-maps-key]
    verify_jwt = false
  [functions.save-booking-payment]
    verify_jwt = false
  [functions.stripe-connect-dashboard]
    verify_jwt = false
  [functions.stripe-connect-onboard]
    verify_jwt = false
  [functions.stripe-connect-status]
    verify_jwt = false
  [functions.unified-checkout]
    verify_jwt = false
  [functions.update-stylist-location]
    verify_jwt = false
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.send-booking-confirmation-email]
    verify_jwt = false
  [functions.send-first-booking-welcome-email]
    verify_jwt = false
  [functions.send-booking-confirmed-email]
    verify_jwt = false
  [functions.send-service-completed-email]
    verify_jwt = false
  [functions.send-signup-welcome-email]
    verify_jwt = false
  [functions.send-stylist-signup-email]
    verify_jwt = false
  [functions.handle-email-events]
    verify_jwt = false
